name: Pester
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test-pwsh:
    strategy:
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests (pwsh)
      run: |
        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -MinimumVersion 5.0.4 -confirm:$false -Force
        Invoke-Pester -Path "tests"        
      shell: pwsh

