name: Pester
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test-pwsh:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Pester tests
      run: |
        Set-PSRepository psgallery -InstallationPolicy trusted
        Install-Module -Name Pester -RequiredVersion 5.6.1 -Confirm:$false -Force
        Invoke-Pester -Path "tests"        
      shell: pwsh
